http:
  routers:
    auth-service:
      rule: "PathPrefix(`/api/v1/auth`) || PathPrefix(`/api/v1/me`)"
      service: auth-service

    organization-service:
      rule: "PathPrefix(`/api/v1/organizations`)"
      service: organization-service

  services:
    auth-service:
      loadBalancer:
        servers:
          - url: "http://auth-service:3000"

    organization-service:
      loadBalancer:
        servers:
          - url: "http://organization-service:3001"