apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
  namespace: sapientia
spec:
  serviceName: auth-db-service
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: openpg
        - name: POSTGRES_PASSWORD
          value: openpgpwd
        - name: POSTGRES_DB
          value: authdb
        volumeMounts:
        - name: auth-db-data
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
  volumeClaimTemplates:
  - metadata:
      name: auth-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
