apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
  namespace: sapientia
spec:
  selector:
    app: auth-db
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None # headless service para StatefulSet