apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: sapientia
type: Opaque
data:
  # Valores em base64 (executar: echo -n "valor" | base64)
  JWT_SECRET: c2FwaWVudGlhc3VwZXJzZWNyZXRrZXk=
  DATABASE_URL: cG9zdGdyZXNxbDovL29wZW5wZzpvcGVucGdwd2RAYXV0aC1kYi1zZXJ2aWNlLnNhcGllbnRpYS5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2F1dGhkYg==
